import os

base = r"C:\Users\ynaka\study_planner"

lines = []
lines.append("import openpyxl")
lines.append("from openpyxl.styles import Font, PatternFill, Alignment, Border, Side")
lines.append("from database import (get_connection, get_plan_v2, get_schedule, get_class_dates_in_range)")
lines.append("from datetime import date, timedelta")
lines.append("from collections import defaultdict")
lines.append("")
lines.append('DOW_JA = ["月", "火", "水", "木", "金", "土", "日"]')
lines.append("")
lines.append("CATEGORY_COLORS = {")
lines.append('    "予習":   "DDEEFF",')
lines.append('    "復習":   "DDFFDD",')
lines.append('    "定着":   "FFFADD",')
lines.append('    "再定着": "FFE5DD",')
lines.append('    "未割当": "F0F0F0",')
lines.append("}")
lines.append("")
lines.append("MASTERY_MULTIPLIER = {1: 1.3, 2: 1.0, 3: 0.5}")
lines.append('CATEGORY_GROUP = {"復習": 0, "定着": 0, "再定着": 0, "予習": 1}')
lines.append("")
lines.append("")
lines.append("def get_adjusted_minutes(item):")
lines.append("    mastery_level = int(item.get('mastery_int', 1) or 1)")
lines.append("    mastery_level = max(1, min(3, mastery_level))")
lines.append("    multiplier = MASTERY_MULTIPLIER.get(mastery_level, 1.0)")
lines.append("    return max(5, round(item['estimated_minutes'] * multiplier / 5) * 5)")
lines.append("")
lines.append("")
lines.append("def priority_score(item):")
lines.append("    group = CATEGORY_GROUP.get(item['category'], 1)")
lines.append("    mastery = int(item.get('mastery_int', 1) or 1)")
lines.append("    review_value = int(item.get('review_value', 3) or 3)")
lines.append("    importance = int(item.get('importance', 3) or 3)")
lines.append("    difficulty = int(item.get('difficulty', 3) or 3)")
lines.append("    return (group, mastery, -review_value, -importance, difficulty)")
lines.append("")
lines.append("")
lines.append("def assign_days_v2(plan, schedule, student_id, start_date_str, end_date_str):")
lines.append("    remaining = {d: m for d, m in schedule.items() if m > 0}")
lines.append("    dates_sorted = sorted(remaining.keys())")
lines.append("    if not dates_sorted:")
lines.append("        for item in plan:")
lines.append("            item['assigned_date'] = None")
lines.append("        return [], plan")
lines.append("    conn = get_connection()")
lines.append("    c = conn.cursor()")
lines.append("    c.execute('SELECT DISTINCT p.subject FROM problems p JOIN assignments a ON p.problem_id = a.problem_id WHERE a.student_id=?', (student_id,))")
lines.append("    subjects = [r['subject'] for r in c.fetchall()]")
lines.append("    conn.close()")
lines.append("    subject_class_dates = {s: get_class_dates_in_range(student_id, s, start_date_str, end_date_str) for s in subjects}")
lines.append("    assigned = []")
lines.append("    unassigned = []")
lines.append("    date_textbook_count = defaultdict(lambda: defaultdict(int))")
lines.append("")
lines.append("    def try_assign(item, search_dates):")
lines.append("        minutes = get_adjusted_minutes(item)")
lines.append("        textbook = item['textbook']")
lines.append("        valid_dates = [d for d in search_dates if remaining.get(d, 0) >= minutes]")
lines.append("        sorted_dates = sorted(valid_dates, key=lambda d: date_textbook_count[d][textbook])")
lines.append("        for d in sorted_dates:")
lines.append("            remaining[d] -= minutes")
lines.append("            item['assigned_date'] = d")
lines.append("            date_textbook_count[d][textbook] += 1")
lines.append("            assigned.append(item)")
lines.append("            return True")
lines.append("        return False")
lines.append("")
lines.append("    plan_sorted = sorted(plan, key=priority_score)")
lines.append("    review_teichaku = [p for p in plan_sorted if p['category'] in ('復習', '定着', '再定着')]")
lines.append("    yosyu = [p for p in plan_sorted if p['category'] == '予習']")
lines.append("")
lines.append("    for item in [p for p in review_teichaku if p['category'] == '復習']:")
lines.append("        class_dates = subject_class_dates.get(item['subject'], [])")
lines.append("        search_from = dates_sorted[0]")
lines.append("        past_classes = [d for d in class_dates if d <= start_date_str]")
lines.append("        if past_classes:")
lines.append("            search_from = past_classes[-1]")
lines.append("        search_dates = [d for d in dates_sorted if d >= search_from]")
lines.append("        if not try_assign(item, search_dates):")
lines.append("            item['assigned_date'] = None")
lines.append("            unassigned.append(item)")
lines.append("")
lines.append("    for item in [p for p in review_teichaku if p['category'] in ('定着', '再定着')]:")
lines.append("        if not try_assign(item, dates_sorted):")
lines.append("            item['assigned_date'] = None")
lines.append("            unassigned.append(item)")
lines.append("")
lines.append("    for item in yosyu:")
lines.append("        class_dates = subject_class_dates.get(item['subject'], [])")
lines.append("        future_classes = sorted([d for d in class_dates if d > start_date_str])")
lines.append("        if future_classes:")
lines.append("            next_class = future_classes[0]")
lines.append("            search_dates = list(reversed([d for d in dates_sorted if d <= next_class]))")
lines.append("        else:")
lines.append("            search_dates = list(reversed(dates_sorted))")
lines.append("        if not try_assign(item, search_dates):")
lines.append("            item['assigned_date'] = None")
lines.append("            unassigned.append(item)")
lines.append("")
lines.append("    return assigned, unassigned")
lines.append("")
lines.append("")
lines.append("def build_plan_data(student_id, start_date_str, target_date_str, subject_filter=None):")
lines.append("    conn = get_connection()")
lines.append("    c = conn.cursor()")
lines.append("    c.execute('SELECT student_id, name, subjects, plan_mode FROM students WHERE student_id=?', (student_id,))")
lines.append("    student = c.fetchone()")
lines.append("    conn.close()")
lines.append("    if not student:")
lines.append("        return None")
lines.append("    all_subjects = [s.strip() for s in student['subjects'].split(',')]")
lines.append("    plan_mode = student['plan_mode'] if student['plan_mode'] else 'all'")
lines.append("    schedule = get_schedule(student_id, start_date_str, target_date_str)")
lines.append("    all_plan = get_plan_v2(student_id, start_date_str, target_date_str)")
lines.append("    if subject_filter:")
lines.append("        subjects = [subject_filter]")
lines.append("        plan = [p for p in all_plan if p['subject'] == subject_filter]")
lines.append("    else:")
lines.append("        subjects = all_subjects")
lines.append("        plan = all_plan")
lines.append("    assigned, unassigned = assign_days_v2(plan, schedule, student_id, start_date_str, target_date_str)")
lines.append("    dates_with_time = sorted([d for d, m in schedule.items() if m > 0])")
lines.append("    order = {'復習': 0, '定着': 1, '再定着': 2, '予習': 3}")
lines.append("    rows = []")
lines.append("    for d in dates_with_time:")
lines.append("        d_obj = date.fromisoformat(d)")
lines.append("        date_label = str(d_obj.month) + '/' + str(d_obj.day) + '（' + DOW_JA[d_obj.weekday()] + '）'")
lines.append("        day_items = [item for item in assigned if item['assigned_date'] == d]")
lines.append("        row = {'date': date_label, 'date_str': d, 'subjects': {}}")
lines.append("        for subject in subjects:")
lines.append("            subject_items = sorted([item for item in day_items if item['subject'] == subject], key=lambda x: order.get(x['category'], 9))")
lines.append("            row['subjects'][subject] = subject_items")
lines.append("        rows.append(row)")
lines.append("    unassigned_by_subject = {}")
lines.append("    for subject in subjects:")
lines.append("        unassigned_by_subject[subject] = [item for item in unassigned if item['subject'] == subject]")
lines.append("    return {'student_name': student['name'], 'student_id': student_id, 'subjects': subjects, 'plan_mode': plan_mode, 'rows': rows, 'unassigned': unassigned_by_subject, 'schedule': schedule}")
lines.append("")
lines.append("")
lines.append("def make_cell_text(item):")
lines.append("    return '【' + item['category'] + '】' + item['textbook'] + ' ' + item['problem_number']")
lines.append("")
lines.append("")
lines.append("def export_excel(target_date_str, output_path, student_id=None, start_date=None, subject_filter=None):")
lines.append("    wb = openpyxl.Workbook()")
lines.append("    wb.remove(wb.active)")
lines.append("    conn = get_connection()")
lines.append("    c = conn.cursor()")
lines.append("    if student_id:")
lines.append("        c.execute('SELECT student_id, name, subjects, plan_mode FROM students WHERE student_id=?', (student_id,))")
lines.append("    else:")
lines.append("        c.execute('SELECT student_id, name, subjects, plan_mode FROM students ORDER BY student_id')")
lines.append("    students = c.fetchall()")
lines.append("    conn.close()")
lines.append("    thin = Side(style='thin')")
lines.append("    border = Border(left=thin, right=thin, top=thin, bottom=thin)")
lines.append("    start_date_str = start_date if start_date else date.today().isoformat()")
lines.append("    for student in students:")
lines.append("        sid = student['student_id']")
lines.append("        name = student['name']")
lines.append("        plan_mode = student['plan_mode'] if student['plan_mode'] else 'all'")
lines.append("        if subject_filter:")
lines.append("            subjects_to_process = [subject_filter]")
lines.append("        elif plan_mode == 'per_subject':")
lines.append("            subjects_to_process = [s.strip() for s in student['subjects'].split(',')]")
lines.append("        else:")
lines.append("            subjects_to_process = None")
lines.append("        if subjects_to_process:")
lines.append("            for subject in subjects_to_process:")
lines.append("                data = build_plan_data(sid, start_date_str, target_date_str, subject)")
lines.append("                if not data:")
lines.append("                    continue")
lines.append("                ws = wb.create_sheet(title=name + '_' + subject)")
lines.append("                _write_excel_sheet(ws, data, border)")
lines.append("        else:")
lines.append("            data = build_plan_data(sid, start_date_str, target_date_str)")
lines.append("            if not data:")
lines.append("                continue")
lines.append("            ws = wb.create_sheet(title=name)")
lines.append("            _write_excel_sheet(ws, data, border)")
lines.append("    wb.save(output_path)")
lines.append("    return output_path")
lines.append("")
lines.append("")
lines.append("def _write_excel_sheet(ws, data, border):")
lines.append("    subjects = data['subjects']")
lines.append("    rows = data['rows']")
lines.append("    unassigned = data['unassigned']")
lines.append("    header_cols = ['実施日']")
lines.append("    for subject in subjects:")
lines.append("        header_cols.append(subject + '（問題）')")
lines.append("        header_cols.append(subject + '（指示）')")
lines.append("    header_cols.append('未割当')")
lines.append("    for col, h in enumerate(header_cols, start=1):")
lines.append("        cell = ws.cell(row=1, column=col, value=h)")
lines.append("        cell.font = Font(bold=True, color='FFFFFF')")
lines.append("        cell.fill = PatternFill('solid', fgColor='4472C4')")
lines.append("        cell.alignment = Alignment(horizontal='center')")
lines.append("        cell.border = border")
lines.append("    order = {'復習': 0, '定着': 1, '再定着': 2, '予習': 3}")
lines.append("    for row_idx, row in enumerate(rows, start=2):")
lines.append("        date_cell = ws.cell(row=row_idx, column=1, value=row['date'])")
lines.append("        date_cell.font = Font(bold=True)")
lines.append("        date_cell.fill = PatternFill('solid', fgColor='E8EEF8')")
lines.append("        date_cell.alignment = Alignment(horizontal='center', vertical='top')")
lines.append("        date_cell.border = border")
lines.append("        col_idx = 2")
lines.append("        for subject in subjects:")
lines.append("            subject_items = sorted(row['subjects'].get(subject, []), key=lambda x: order.get(x['category'], 9))")
lines.append("            problem_lines = []")
lines.append("            instruction_lines = []")
lines.append("            for item in subject_items:")
lines.append("                problem_lines.append(make_cell_text(item))")
lines.append("                instruction_lines.append(item.get('instruction', '') or '')")
lines.append("            problem_text = chr(10).join(problem_lines)")
lines.append("            instruction_text = chr(10).join(instruction_lines)")
lines.append("            color = 'FFFFFF'")
lines.append("            if subject_items:")
lines.append("                color = CATEGORY_COLORS.get(subject_items[0]['category'], 'FFFFFF')")
lines.append("            prob_cell = ws.cell(row=row_idx, column=col_idx, value=problem_text)")
lines.append("            if subject_items:")
lines.append("                prob_cell.fill = PatternFill('solid', fgColor=color)")
lines.append("            prob_cell.alignment = Alignment(horizontal='left', vertical='top', wrap_text=Tru